DROP DATABASE IF EXISTS application;
CREATE DATABASE application WITH ENCODING 'UTF-8' LC_CTYPE='en_US.UTF8' LC_COLLATE='en_US.UTF8' TEMPLATE=template0;
GRANT ALL PRIVILEGES ON DATABASE application to %(username)s;
